version: "3.9"

services:
  web:
    platform: linux/amd64
    build:
      context: .
    container_name: image-scoring-container
    ports:
      - "8080:8080"
    environment:
      - NAME=World
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8080
